<?php
// @file: default.homepage.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<div class="igk-container">
<div class="igk-row">
<div class="igk-col">
<div>
<div style="margin-bottom: 4em" ></div>
<h2>Bienvenue sur la plateform Balafon</h2>
	<div class="fm-title">BALAFON <?= IGK_VERSION; ?></div>
</div>
</div>
</div>
</div>
<?php
$c=igk_createNode("container");
$c->addRow()->addCol("igk-col-3-3 igk-col-xsm-3-3  igk-col-sm-3-3")->addDiv()->addObData(function(){
	$buri = igk_io_baseuri();
    ?>
<div style="line-height:2.8em">
	<p >Merci d'avoir choisi BALAFON comme plate forme de développement web. </p>
	<p class="igk-danger igk-panel" style="line-height:1.8em; font-size: 0.8em; font-weight: 100;">
		Oups!!! Le system ne détecte pas de contrôleur principal.
	</p>
<div class="mfo" >
	Pour plus d'information ... <a href="//igkdev.com/balafon/wiki"> consulté la documentation</a>
</div>
<div class="mfo igk-button">
	<a href="<?= $buri ?>/Configs">Configuration</a>
</div>
</div>
<?php
});
$c->RenderAJX();
