<?php
// @file: class.igkhtmlphpcodeitem.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description: 
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
Represente une zone permettant d'encapsuler du code php. Ce code sera evalué par la function <b>eval</b> dans le contexte du noeud parent.
