<?php
// @file: utility.phtml
// @author: C.A.D. BONDJE DOUE
// @description: 
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

use IGKApi\UtilityActions;
igk_google_addfont($doc, "Roboto");
$t->clearChilds();
igk_view_handle_actions($fname, new UtilityActions($this, $t), $params);
$t->setStyle("font-weight: 100");
$t->setClass("google-Roboto");
$doc->Title="Utility service";
$t->addSectionTitle(4)->Content="Api Utility Service";